### ISSUE TITLE
No tts (you litterally compared 2 memory addresses) (insert facepalm here)

### ISSUE THREAD

**Issue by Fearvel** [Tarutella/titan-jail-plugin#2]
line 513
if (players[i] == players[yourIndex])
Did you ever heared of string.Compare() ???????
Learn the difference between  == and string.Compare()

**Comment by Tarutella** [comment]
chill out :P 
I never actually used visual studio nor C# before that, I only used it cause it was enforced by ACT. 
anyhow, in latest release I shard, TTS is working just fine. maybe you downloaded the wrong release.
and thanks for cleaning this up, and using better ways of comparing, I didn't intend to clean or organize the code.
also I think it would've been fine to just compare the indexes and that's it.. like 
line 513
if (i == yourIndex)
but I guess it doesn't matter.
