### ISSUE TITLE
Using plugin for J client

### ISSUE THREAD

**Issue by kotorichun77** [Tarutella/titan-jail-plugin#3]
Hi, I believe your plugin is only for E client as the placeholder you use for the boss name in the expression :[a-zA-Z-']+?:2B6(B|C):.?:.?: is english letters only. Is it possible edit this somehow to fit JP boss name? Currently in a JP static so I'm the only one who can get it to work. Thank you.

**Comment by Tarutella** [comment]
updated Regex, thanks
